SELECT R.FOOD_TYPE, R.REST_ID, R.REST_NAME, R.FAVORITES
FROM (SELECT FOOD_TYPE, Max(FAVORITES) FAVORITES
      FROM REST_INFO 
      GROUP BY FOOD_TYPE
     ORDER BY FAVORITES DESC) A, REST_INFO R
WHERE A.FOOD_TYPE = R.FOOD_TYPE
AND A.FAVORITES = R.FAVORITES
GROUP BY R.FOOD_TYPE
ORDER BY R.FOOD_TYPE DESC;