SELECT B.CATEGORY, SUM(BS.SALES) TOTAL_SALES
FROM BOOK B
LEFT JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE YEAR(BS.SALES_DATE) = '2022' AND MONTH(BS.SALES_DATE) = '01'
GROUP BY CATEGORY
ORDER BY CATEGORY;
