SELECT YEAR(E.DIFFERENTIATION_DATE) YEAR, 
M.MAX_SIZE-E.SIZE_OF_COLONY YEAR_DEV, E.ID
FROM ECOLI_DATA E
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) Y, MAX(SIZE_OF_COLONY) MAX_SIZE
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE) 
) M
ON YEAR(E.DIFFERENTIATION_DATE) = M.Y
ORDER BY YEAR, YEAR_DEV;
