SELECT SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM (
    SELECT SUM(SCORE) SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL, 
           ROW_NUMBER() OVER (ORDER BY SUM(SCORE) DESC) RN
    FROM HR_EMPLOYEES
    JOIN HR_GRADE USING (EMP_NO)
    GROUP BY EMP_NO
) R
WHERE RN = 1;
